version: '3.5'

services:
  db:
    container_name: db
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zenlms
    restart: always

  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
     - 8080:8080

  web:
    container_name: adonis_container
    image: adonis/zenlms:1.1
    ports:
      - 3333:3333
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: node ace migration:run

volumes:
  postgres_volume:


